// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oggwqglbungujhxuftcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nZ3dxZ2xidW5ndWpoeHVmdGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjU1NzUsImV4cCI6MjA1Njk0MTU3NX0.wZ2sJ6YWfU3I42tcDkJ4KDYYxEA-wSwt4kmAxd0D7V0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);